/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:c3e80572-d2f6-47d1-98b0-f0faf0e0dbcf",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_j0hiI0mBc",
    "aws_user_pools_web_client_id": "1uhogrbevhokvsmlk2mp8b2p3a",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://orbqw6omxjfhbaxsig7twx53lu.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-yw7ljrscovduxan4byvj5idp7e",
    "aws_user_files_s3_bucket": "amplifyapp4b8a6734123c4f23a157fc51466de435105247-staging",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
